image: gitlab-registry.insee.fr/kubernetes/images/build/r-toolbox/onyxia-rstudio-insee:r4.2.1

stages:
  - deploy

pages:
  stage: deploy
  tags:
    - docker
  script:
    - wget -q "https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.361/quarto-1.3.361-linux-arm64.deb" -O quarto.deb
    - dpkg -i quarto.deb
    - quarto check install
    - rm quarto.deb
    - Rscript -e 'install.packages("quarto") ; quarto::quarto_render()'
    - mkdir -p public
    - mv _site/* public/
  artifacts:
    paths:
      - public
  only:
    - master
