image: gitlab-registry.insee.fr/kubernetes/images/build/r-toolbox/onyxia-rstudio-insee:r4.2.1

stages:
  - deploy

pages:
  stage: deploy
  tags:
    - docker
  script:
    - Rscript -e 'install.packages("quarto") ; quarto::quarto_render()'
    - mkdir -p public
    - mv _site/* public/
  artifacts:
    paths:
      - public
  only:
    - master
