project:
  type: website

website:
  title: "Annotation appariements"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: pairs.qmd
        text: "Annotation paires"
      - href: multiple.qmd
        text: "Choix entre plusieurs appariements"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



