project:
  type: website

website:
  title: "Annotation appariements"
  navbar:
    left:
      - href: index.qmd
        text: "Page principale"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



